### ISSUE TITLE
Failed to activate tree-view

### ISSUE THREAD

**Issue by mdotasia** [DanBrooker/file-icons#468]
[Enter steps to reproduce below:]

1. Update plugin from 1.7.25 to 2.0.0 on Windows
2. Restart Atom

I get error **Failed to activate tree-view** package. This has been reported here: https://github.com/atom/tree-view/issues/993. Worked fine with 1.7.25 on Win and no issues on macOS.

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [file-icons](https://github.com/DanBrooker/file-icons) package, v2.0.0

### Stack Trace

Failed to activate the file-icons package

```
At path.replace is not a function

TypeError: path.replace is not a function
    at Repository.relativize (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\git-utils\lib\git.js:199:19)
    at GitRepository.module.exports.GitRepository.relativize (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\src\git-repository.js:163:29)
    at GitRepository.module.exports.GitRepository.getCachedPathStatus (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\src\git-repository.js:271:33)
    at File.watchRepo (C:\Users\thilo.maier\.atom\packages\file-icons\lib\filesystem\file.js:395:27)
    at new File (C:\Users\thilo.maier\.atom\packages\file-icons\lib\filesystem\file.js:31:8)
    at FileRegistry.get (C:\Users\thilo.maier\.atom\packages\file-icons\lib\filesystem\file-registry.js:65:17)
    at IconService.iconClassForPath (C:\Users\thilo.maier\.atom\packages\file-icons\lib\service\icon-service.js:29:29)
    at tree-view-file.module.exports.FileView.initialize (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\tree-view\lib\file-view.js:35:42)
    at tree-view-directory.DirectoryView.createViewForEntry (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\tree-view\lib\directory-view.js:133:12)
    at C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\tree-view\lib\directory-view.js:104:26
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\atom-keymap\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\atom-keymap\node_modules\event-kit\lib\emitter.js:125:28)
    at Directory.module.exports.Directory.reload (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\tree-view\lib\directory.js:370:29)
    at Directory.module.exports.Directory.expand (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\tree-view\lib\directory.js:383:12)
    at tree-view-directory.DirectoryView.expand (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\tree-view\lib\directory-view.js:178:24)
    at tree-view-directory.DirectoryView.initialize (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\tree-view\lib\directory-view.js:82:21)
    at TreeView.<anonymous> (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\tree-view\lib\tree-view.js:616:16)
    at TreeView.module.exports.TreeView.updateRoots (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\tree-view\lib\tree-view.js:621:10)
    at Object.consumeFileIcons (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\tree-view\lib\main.js:101:50)
    at Provider.module.exports.Provider.provide (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\service-hub\lib\provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.provide (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\service-hub\lib\service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:362:71)
    at Package.module.exports.Package.activateNow (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:187:16)
    at C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:157:32
    at Package.module.exports.Package.measure (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:92:15)
    at C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:150:26
    at Package.module.exports.Package.activate (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package-manager.js:352:19
    at C:\Users\thilo.maier\AppData\Local\atom\app-1.12.7\resources\app.asar\src\config.js:635:20
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "whitespace"
    ],
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.16.1 (inactive)
compare-files, v0.8.0 (active)
editorconfig, v2.0.5 (active)
file-icons, v2.0.0 (inactive)
language-gitignore, v0.3.0 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
linter-htmlhint, v1.3.1 (active)
linter-jsonlint, v1.3.0 (active)
linter-stylelint, v3.6.0 (active)
markdown-pdf, v1.5.0 (inactive)
minimap, v4.25.7 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-linter, v1.6.0 (active)
minimap-selection, v4.4.0 (active)
react, v0.16.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Alhadis** [comment]
Have you restarted Atom?

**Comment by Alhadis** [comment]
@mdotasia I've published a hotfix. Please let me know if this error reoccurs after installing v2.0.1.

**Comment by DaMitchell** [comment]
Fixed it for me. Thanks.

**Comment by mdotasia** [comment]
@Alhadis Fixed it. Thanks!
